# -*- coding:utf-8 -*-
"""
_header格式：{表名: Header对象}
表名为None表示默认sheet或csv文件
未设置header时值为None
"""
from csv import writer as csv_writer
from io import TextIOWrapper
from pathlib import Path
from typing import Any, Optional, Union, List, Dict, Tuple, Iterable

from openpyxl.worksheet.worksheet import Worksheet

from .base import BaseRecorder
from .setter import RecorderSetter
from .cell_style import CellStyle
from .tools import Header, RowData


class Recorder(BaseRecorder):
    _data: Union[dict, list] = ...
    data: Union[dict, list] = ...
    _style_data: dict = ...
    _set: RecorderSetter = ...
    _row_height: Optional[float] = ...
    _follow_styles: bool = ...
    _styles: Union[CellStyle, List[CellStyle], Tuple[CellStyle], Dict[str, CellStyle], None] = ...
    _quote_char: str = ...
    _delimiter: str = ...
    _header: Dict[Optional[str], Optional[Header]] = ...
    _header_row: int = ...
    _fast: bool = ...
    _methods: dict = ...
    data_col: int = ...
    _link_style: Optional[CellStyle] = ...

    def __init__(self, path: Union[str, Path] = None, cache_size: int = 1000): ...

    def _set_methods(self, file_type: str) -> None: ...

    @property
    def set(self) -> RecorderSetter: ...

    @property
    def delimiter(self) -> str: ...

    @property
    def quote_char(self) -> str: ...

    @property
    def header(self) -> Header: ...

    def add_data(self, data: Any,
                 coord: Union[list, Tuple[Union[None, int, str], Union[int, str]], str, int] = 'newline',
                 table: Union[str, bool] = None) -> None: ...

    def _add_data_fast(self, **args) -> None: ...

    def _add_data_slow(self, **args) -> None: ...

    def set_link(self,
                 coord: Union[int, str, tuple, list],
                 link: Union[str, dict],
                 content: Union[None, int, str, float] = None,
                 table: Union[str, bool] = None) -> None: ...

    def set_img(self,
                coord: Union[int, str, tuple, list],
                img_path: Union[None, str, Path, dict],
                width: float = None,
                height: float = None,
                table: Union[str, bool] = None) -> None: ...

    def set_style(self,
                  coord: Union[int, str, tuple, list],
                  style: Union[CellStyle, dict],
                  replace: bool = True,
                  table: Union[str, bool] = None) -> None: ...

    def set_row_height(self, row: Union[int, str], height: float,
                       table: Union[str, bool] = None) -> None: ...

    def set_col_width(self, col: Union[int, str], width: float,
                      table: Union[str, bool] = None) -> None: ...

    def _set_link(self,
                  coord: Union[int, str, tuple, list],
                  link: Union[str, dict],
                  content: Union[None, int, str, float] = None,
                  table: Union[str, bool] = None) -> None: ...

    def _set_img(self,
                 coord: Union[int, str, tuple, list],
                 img_path: Union[None, str, Path, dict],
                 width: float = None,
                 height: float = None,
                 table: Union[str, bool] = None) -> None: ...

    def _set_style(self,
                   coord: Union[int, str, tuple, list],
                   style: Union[CellStyle, dict],
                   replace: bool = True,
                   table: Union[str, bool] = None) -> None: ...

    def _set_row_height(self, row: Union[int, str], height: float,
                        table: Union[str, bool] = None) -> None: ...

    def _set_col_width(self, col: Union[int, str], width: float,
                       table: Union[str, bool] = None) -> None: ...

    def rows(self,
             key_cols: Union[str, int, list, tuple, bool] = True,
             sign_col: Union[str, int, True] = True,
             is_header: bool = False,
             signs: Any = None,
             deny_sign: bool = False,
             count: int = None,
             begin_row: Optional[int] = None) -> List[RowData]: ...

    def clear(self) -> None: ...

    def _record(self) -> None: ...

    def _to_fast_mode(self) -> None: ...

    def _to_slow_mode(self) -> None: ...

    def _to_xlsx_fast(self) -> None: ...

    def _to_csv_fast(self) -> None: ...

    def _to_xlsx_slow(self) -> None: ...

    def _to_csv_slow(self) -> None: ...

    def _to_txt(self) -> None: ...

    def _to_jsonl(self) -> None: ...

    def _to_json(self) -> None: ...


def get_header(recorder: Recorder, ws: Worksheet = None) -> Header: ...


def new_sheet_fast(recorder: Recorder, ws: Worksheet, data: list, first_wrote: bool) -> bool: ...


def new_sheet_slow(recorder: Recorder, ws: Worksheet, data: list,
                   style: list, first_data_wrote: bool, first_style_wrote: bool): ...


def get_xlsx_rows(recorder: Recorder,
                  header: Header, key_cols: Union[list, True],
                  begin_row: Optional[int], sign_col: Union[str, int, bool], sign: Any,
                  deny_sign: bool, count: int, ws: Worksheet) -> List[RowData]: ...


def get_csv_rows(recorder: Recorder,
                 header: Header, key_cols: Union[list, True],
                 begin_row: Optional[int], sign_col: Union[str, int, bool], sign: Any,
                 deny_sign: bool, count: int, ws: Worksheet) -> List[RowData]: ...


def handle_xlsx_rows_with_count(key_cols: Union[list, True], deny_sign: bool, header: Header, rows,
                                begin_row: Optional[int], sign_col,
                                sign, count: int) -> List[RowData]: ...


def handle_xlsx_rows_without_count(key_cols: Union[list, True], deny_sign: bool, header: Header, rows,
                                   begin_row: Optional[int],
                                   sign_col, sign) -> List[RowData]: ...


def handle_csv_rows_with_count(lines, begin_row: Optional[int], sign_col, sign, deny_sign: bool,
                               key_cols: Union[list, True], res,
                               header: Header, count: int) -> List[RowData]: ...


def handle_csv_rows_without_count(lines, begin_row: Optional[int], sign_col, sign, deny_sign: bool,
                                  key_cols: Union[list, True], res,
                                  header: Header) -> List[RowData]: ...


def get_and_set_csv_header(recorder: Recorder, new_csv: bool, file: TextIOWrapper, writer: csv_writer) -> None: ...


def data2ws_no_style(ws: Worksheet, header: Header, row: int, col: int, data: list, not_new: bool,
                     max_row: int, rewrite: bool) -> bool: ...


def data2ws_has_style(ws: Worksheet, header: Header, row: int, col: int, data: list, not_new: bool,
                      max_row: int, rewrite: bool) -> bool: ...


def data2ws_no_style_rewrite(ws: Worksheet, header: Header, row: int, col: int, data: list, not_new: bool,
                             max_row: int, rewrite: bool) -> bool: ...


def data2ws_has_style_rewrite(ws: Worksheet, header: Header, row: int, col: int, data: list, not_new: bool,
                              max_row: int, rewrite: bool) -> bool: ...


def set_link_to_ws(ws: Worksheet, data: list, empty: bool, recorder: Recorder) -> None: ...


def set_img_to_ws(ws: Worksheet, data: list, empty: bool, recorder: Recorder) -> None: ...


def set_style_to_ws(ws: Worksheet, data: list, empty: bool, recorder: Recorder, header: Header) -> None: ...


def set_style(height: float, styles: List[CellStyle], ws: Worksheet, row: int) -> None: ...


def copy_some_row_style(ws: Worksheet, row: int, styles: List[Iterable]) -> None: ...


def copy_full_row_style(ws: Worksheet, row: int, cur_data: list) -> None: ...


def copy_part_row_style(ws: Worksheet, row: int, cur_data: list, col: int) -> None: ...
