# -*- coding:utf-8 -*-
from pathlib import Path
from typing import Union, Any, Optional, List, Tuple, Dict

from .base import OriginalRecorder, BaseRecorder
from .cell_style import CellStyle
from .db_recorder import DBRecorder
from .recorder import Recorder
from .tools import Header


class OriginalSetter(object):
    _recorder: OriginalRecorder = ...

    def __init__(self, recorder: OriginalRecorder): ...

    def cache_size(self, size: int) -> OriginalSetter: ...

    def path(self, path: Union[str, Path]) -> OriginalSetter: ...

    def show_msg(self, on_off: bool) -> OriginalSetter: ...

    def auto_backup(self,
                    interval: int = None,
                    path: Union[str, Path] = None,
                    new_name: bool = None) -> OriginalSetter: ...


class BaseSetter(OriginalSetter):
    _recorder: BaseRecorder = ...

    def table(self, name: Union[str, bool]) -> BaseSetter: ...

    def before(self, data: Any) -> BaseSetter: ...

    def after(self, data: Any) -> BaseSetter: ...

    def encoding(self, encoding: str) -> BaseSetter: ...

    def _set_after_before(self, before: bool, data: Any): ...


class RecorderSetter(BaseSetter):
    _recorder: Recorder = ...

    def __init__(self, recorder: Recorder): ...

    # -------------------上级开始-------------------

    def cache_size(self, size: int) -> RecorderSetter: ...

    def show_msg(self, on_off: bool) -> RecorderSetter: ...

    def auto_backup(self,
                    interval: int = None,
                    path: Union[str, Path] = None,
                    new_name: bool = None) -> RecorderSetter: ...

    def table(self, name: Union[str, bool, None]) -> RecorderSetter: ...

    def before(self, before: Any) -> RecorderSetter: ...

    def after(self, after: Any) -> RecorderSetter: ...

    # -------------------上级结束-------------------

    def header(self, head: Union[list, tuple], table: str = None,
               to_file: bool = True, row: int = None) -> RecorderSetter: ...

    def header_row(self, num: int) -> RecorderSetter: ...

    def encoding(self, encoding: str) -> RecorderSetter: ...

    def delimiter(self, delimiter: str) -> RecorderSetter: ...

    def quote_char(self, quote_char: str) -> RecorderSetter: ...

    def follow_styles(self, on_off: bool = True) -> RecorderSetter: ...

    def file_type(self, file_type: str) -> RecorderSetter: ...

    def default_row_height(self, height: float) -> RecorderSetter: ...

    def default_styles(self, styles: Union[
        CellStyle, List[CellStyle], Tuple[CellStyle, ...], Dict[Any, CellStyle], None]) -> RecorderSetter: ...

    def path(self, path: Union[str, Path], file_type: str = None) -> RecorderSetter: ...

    def auto_new_header(self, on_off: bool = True) -> RecorderSetter: ...

    def data_col(self, col: Union[str, int]) -> RecorderSetter: ...

    def link_style(self, style: Union[CellStyle, True] = True) -> RecorderSetter: ...


class DBSetter(BaseSetter):
    _recorder: DBRecorder = ...

    def __init__(self, recorder: DBRecorder): ...

    # -------------------上级开始-------------------

    def cache_size(self, size: int) -> DBSetter: ...

    def show_msg(self, on_off: bool) -> DBSetter: ...

    def auto_backup(self,
                    interval: int = None,
                    path: Union[str, Path] = None,
                    new_name: bool = None) -> DBSetter: ...

    def table(self, name: Union[str, bool]) -> DBSetter: ...

    def before(self, before: Any) -> DBSetter: ...

    def after(self, after: Any) -> DBSetter: ...

    def encoding(self, encoding: str) -> DBSetter: ...

    # -------------------上级结束-------------------

    def path(self, path: Union[str, Path], table: Optional[str] = None) -> DBSetter: ...


def set_csv_header(recorder: Recorder,
                   header: Header,
                   row: int) -> None: ...


def set_xlsx_header(recorder: Recorder,
                    header: Header,
                    table: str,
                    row: int) -> None: ...
