# -*- coding:utf-8 -*-
from io import TextIOWrapper
from pathlib import Path
from typing import Union, Tuple, Any, Optional, List, Dict, Iterable

from openpyxl.workbook import Workbook
from openpyxl.worksheet.worksheet import Worksheet

from .base import BaseRecorder
from .recorder import Recorder


def remove_end_Nones(in_list: list) -> list: ...


class BaseHeader(object):
    _NUM_KEY: dict = ...
    _KEY_NUM: dict = ...
    _CONTENT_FUNCS: dict = ...

    @property
    def key_num(self) -> Dict[str, int]: ...

    @property
    def num_key(self) -> Dict[int, str]: ...

    def __iter__(self): ...


class Header(BaseHeader):

    def __init__(self, header: Union[list, tuple] = None): ...

    def __getitem__(self, item: Union[int, str]): ...

    def __len__(self) -> int: ...

    def values(self): ...

    def items(self): ...

    def make_row_data(self, row: int, row_values: dict, None_val: Optional[''] = None) -> RowData: ...

    def make_insert_list(self, data, auto_new: bool, rewrite: bool, file_type: Optional[str]) -> Tuple[list, bool]: ...

    def make_change_list(self, line_data, data, col, auto_new, rewrite, file_type): ...

    def make_num_dict(self, data: dict, file_type: Optional[str]) -> dict: ...

    def get_key(self, num: int) -> Union[str, int]: ...

    def get_num(self, col: Union[int, str], is_header: bool = True) -> Optional[int]: ...


class ZeroHeader(Header):
    _OBJ: ZeroHeader = ...


class RowData(dict):
    header: Header = ...
    row: int = ...
    None_val: Optional[''] = ...

    def __init__(self, row: int, header: Header, None_val: Optional[''], seq: dict): ...

    def val(self, key: Union[int, str], is_col: bool = False, coord: bool = False) -> Any: ...


def align_csv(path: Union[str, Path], encoding: str = 'utf-8', delimiter: str = ',', quotechar: str = '"') -> None: ...


def get_usable_path(path: Union[str, Path], is_file: bool = True, parents: bool = True) -> Path: ...


def make_valid_name(full_name: str) -> str: ...


def get_long(txt) -> int: ...


def parse_coord(coord: Union[int, str, list, tuple, None] = None, data_col: int = None) -> Tuple[
    Optional[int], int]: ...


def process_content_xlsx(content: Any) -> Union[None, int, str, float]: ...


def process_content_json(content: Any) -> Union[None, int, str, float]: ...


def process_content_str(content: Any) -> str: ...


def ok_list_xlsx(data_list: Iterable) -> list: ...


def ok_list_str(data_list: Iterable) -> list: ...


def ok_list_db(data_list: Iterable) -> list: ...


def get_usable_coord_int(coord: Union[tuple, list],
                         max_row: int,
                         max_col: Union[int, Worksheet]) -> Tuple[int, int]: ...


def get_usable_coord(coord: Union[tuple, list],
                     max_row: int,
                     ws: Worksheet) -> Tuple[int, int]: ...


def data_to_list_or_dict_simplify(recorder: BaseRecorder,
                                  data: Union[list, tuple, dict, None]) -> Union[list, dict]: ...


def data_to_list_or_dict(recorder: BaseRecorder, data: Union[list, tuple, dict, None]) -> Union[list, dict]: ...


def get_csv(recorder: Recorder) -> Tuple[TextIOWrapper, bool]: ...


def get_wb(recorder: Recorder) -> tuple: ...


def get_ws(wb: Workbook, table, tables, new_file) -> Tuple[Worksheet, bool]: ...


def fix_openpyxl_bug(recorder, wb, ws, table) -> tuple: ...


def get_tables(path: Union[str, Path]) -> list: ...


def do_nothing(*args, **kwargs) -> None: ...


def get_key_cols(cols: Union[str, int, list, tuple, bool], header: Header, is_header: bool) -> List[int]: ...
